version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=lms
      - POSTGRES_USER=lmsuser
      - POSTGRES_PASSWORD=lmspassword

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    build: .
    command: ./wait-for-it.sh db:5432 -- gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=lms
      - DB_USER=lmsuser
      - DB_PASS=lmspassword

volumes:
  postgres_data:
